import { createContext } from "react";

export  const RobotsContext = createContext([
          {key:"1",
          mainImg:'1',
          tag:"Mixed",
          title:"AlphaX34523",
          timeFrame:"30min",
          riskPercent:"3",
          tutorImg:'1',
          tutorName:"Leonard Victor" ,
          priceTag:"75.00",
          minDerivBal:"400", 
          tradeMarkets:["GBPUSD", "XAUUSD", "AUDUSD", "GBPJPY", "USDJPY", "AUDCAD"],
          aMT:50,
          winRate:"5% - 25%" ,
          variation:"c_Val-5,Line-Val-10"},
          { 
           key:"2",
           mainImg:'2',
           tag:"Metal",
           title:"MetalG88719Z",
           timeFrame:"1hrs",
           riskPercent:"6",
           tutorImg:'2',
           tutorName:"Jeffrey Williams" ,
           priceTag:"62.00",
           minDerivBal:"500", 
          tradeMarkets:["XAUEUR", "XAUUSD", "XAUGBP", "XAGUSD", "XPTUSD"],
          aMT:10,
          winRate:"10% - 15%" ,
          variation:"c_Val-20,Line-Val-15"
           },
           { 
           key:"3",
           mainImg:'3',
           tag:"Commodity",
           title:"CommodulJ7879",
           timeFrame:"5min",
           riskPercent:"5",
           tutorImg:'2',
           tutorName:"Claretta Mason" ,
           priceTag:"55.00",
           minDerivBal:"100", 
          tradeMarkets:["GBPUSD", "USDCAD", "AUDUSD", "GBPJPY", "USDJPY", "AUDCAD"],
          aMT:200,
          winRate:"2% - 30%" ,
          variation:"c_Val-5,Line-Val-10"
           },
           { 
           key:"4",
           mainImg:'4',
           tag:"Cryptocurrency",
           title:"BlockRobot0x809273",
           timeFrame:"4hrs",
           riskPercent:"23",
           tutorImg:'4',
           tutorName:"Jessica Duke" ,
           priceTag:"45.00",
           minDerivBal:"300", 
          tradeMarkets:["Bitcoin","Tether","Litcoin","Ethereum","BTCLTC"],
          aMT:20,
          winRate:"5% - 20%" ,
          variation:"c_Val-8,Line-Val-10"
           },
           { 
           key:"5",
           mainImg:'5',
           tag:"Stock",
           title:"StockHackathon500",
           timeFrame:"1 day",
           riskPercent:"3",
           tutorImg:'5',
           tutorName:"Samuel Jacobs" ,
           priceTag:"25.00",
           minDerivBal:"400", 
          tradeMarkets:["Apple", "Amazon", "Microsoft", "Tesla", "Visa"],
          aMT:10,
          winRate:"5% - 25%" ,
          variation:"c_Val-5,Line-Val-25"
           },
           { 
           key:"6",
           mainImg:'6',
           tag:"Custom",
           title:"Build your Robot",
           timeFrame:"custom",
           riskPercent:"custom",
           tutorImg:'6',
           tutorName:"Custom Builder" ,
           priceTag:"10.00",
           },
])

  